packages:
  - "apps/*"
  - "packages/*"


catalog:
  eslint: ^8
  prettier: ^3.3.3
  typescript: 5.5.4

catalogs:
  react19:
    react: 19.0.0-rc-66855b96-20241106
    react-dom: 19.0.0-rc-66855b96-20241106
    "@types/react": 18.3.1
    "@types/react-dom": 18.3.0
